language: python
python:
  - "2.7"
install:
  - pip install -r requirements-dev.txt --use-wheel
  - pip install -e . --use-wheel
script:
  - ./run_tests.sh
after_success:
  - coveralls
deploy:
  provider: pypi
  user: Praekelt
  password:
    secure: "J1MNwJXIM2WNIsCFMRtJuOKNRiBfpc63C8ZNOYtlnl7XPyKQK0bR7iZYdXVpDRzuzeq1p9fdLLvG6mJijwIIY2RhRV6+oRzWKAR/ab0XC9+D7dAkfSMz9nrOtAOsr9CPlwenurK3+N9NrdFv9lxiU/O3Kyv1cX1u2H9E/t03zn8="
  on:
    tags: true
    all_branches: true
